version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  
    commands:
      - pip install boto3  

  build:
    commands:
      - npm install
      - npm run build
      - npm run test

  post_build:
    on-failure:
      commands:
        - echo "Build failed, executing script..."
        - python3 script.py  # Your email notification script

artifacts:
  files: "**/*"
  base-directory: ./
  name: compiled.zip
